
import static java.nio.channels.AsynchronousFileChannel.open;
import static java.nio.channels.AsynchronousFileChannel.open;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.*;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ravi
 */
public class modifyprofile extends javax.swing.JFrame {
    //decalre public variables
    public String usrmatch="false";
    private String usrname;
    public String admin;
    PreparedStatement stm1;//declare variable
    Connection con;
    /**
     * Creates new form modifyprofile
     */
    public modifyprofile() {//main class
        initComponents();
        Connection con;
        //set values to not editable
        age.setEditable(false);
        name.setEditable(false);
        sex.setEnabled(false);
        dob.setEnabled(false);
        
        sex.setSelectedIndex(-1);
        
        update.setEnabled(false);
        
           }
    
    public modifyprofile(String val1){//create constructor of modify profile
         initComponents();
        Connection con;
        
        age.setEditable(false);//set editable to false
        name.setEditable(false);//set editable to false
        sex.setEnabled(false);//set editable to false
        dob.setEnabled(false);//set editable to false
        
        sex.setSelectedIndex(-1);
        
        update.setEnabled(false);//set enable to false
        
        this.admin = val1;// store variable passed
        
        title.setText("Hi!! " + val1);//set title
     
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        sex = new javax.swing.JComboBox<>();
        dob = new com.toedter.calendar.JDateChooser();
        update = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        username = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("SIGN-UP");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 100, 40));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Sign-out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 30, 100, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Modify User Profile");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 357, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Sex");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 101, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("NAME");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 101, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Age");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 101, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Date of birth");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 101, 30));

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 388, 30));
        getContentPane().add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 388, 30));

        sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        getContentPane().add(sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 388, 30));
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 510, 388, 30));

        update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 620, 120, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Username");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 101, 30));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 100, 40));

        clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 620, 120, 40));
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 224, 30));

        jLabel11.setText("@PIXABAY");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 120, -1, -1));

        title.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        title.setText("HI ADMIN");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 190, 29));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.jpeg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1080, 640));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/white.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 110));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      
        
        if(username.getText().length() == 0){//if username is empty display message
            JOptionPane.showMessageDialog(this, "Please Enter the User Name to Update ");
        }
        
        
        else{ //else execute the query
                try {
                    Connection con;//declare variable
                    ResultSet rs;
                    String usrname=username.getText();
                    String query = "select * from flight_booking.Cust_Info where Email_ID='" + usrname + "'";//query

                    //connection driver
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver"); //Connection driver
                    con = DriverManager.getConnection("jdbc:sqlserver://flightbookingsystem01.database.windows.net:1433;database=flight_booking_system;user=Aritra@flightbookingsystem01;password=Flightbooking_1234;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;");//Connection string

                    Statement stm = con.createStatement();
                    rs = stm.executeQuery(query);//execute statement
                    usrmatch="true";

                    if (rs.next()) {//if results are present
                        
                        //set result values into variable
                        String Age = rs.getString("Age");
                        String Name=rs.getString("First_Name");
                        String Dob=rs.getString("DOB");
                        String Sex = rs.getString("Sex");


                        DateFormat Date = new SimpleDateFormat("yyyy-MM-dd");
                        java.util.Date date = Date.parse(Dob);

                        //set variables into the window
                        age.setText(Age);
                        name.setText(Name);
                        dob.setDate(date);
                        sex.setSelectedItem(Sex);

                        age.setEditable(true);//set everything to editable
                        name.setEditable(true);
                        sex.setEnabled(true);
                        dob.setEnabled(true);

                        update.setEnabled(true);//enable update button

                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Account Doesnot exist");//else display account dows not exist
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(modifyprofile.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(modifyprofile.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ParseException ex) {
                    Logger.getLogger(modifyprofile.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        
        
        ResultSet rs;//declare variable
        String usrname=username.getText();//get text from window
        String Name=name.getText();//get text from window
        String Age=age.getText();//get text from window
        String Sex = sex.getSelectedItem().toString();
        
        
        
        
        
        
        java.sql.Date Date = new java.sql.Date(dob.getDate().getTime()); //Used calender jar file to get date and time
        String DOB = Date.toString();//change dob into string
        
        
         long todaydate = System.currentTimeMillis();//get today
            java.sql.Date date = new java.sql.Date(todaydate);//change today into date
           String todaysdate=date.toString();//change date into string
           
           
           if(DOB.compareTo(todaysdate) >0){//compare dob with today date, show error if dob is f=grater than today date
               
                JOptionPane.showMessageDialog(this, "Your age cannot be greater than today's date. Please check your date of birth");
                 
                }
           
           else if(Age.length()==0)//if field is kept empty show error message
                {
                JOptionPane.showMessageDialog(this, "Please enter User's Age");
                age.setText("");
                
                age.requestFocus();
                }
            else if(Name.length()==0)//if field is kept empty show error message
                    {
                    JOptionPane.showMessageDialog(this, "Please enter User's Name");
                    name.setText("");

                    name.requestFocus();
                    }
           
           
            else{//else update the table
        
        
                    try {
                        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver"); //Connection driver
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(modifyprofile.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    try {
                        con = DriverManager.getConnection("jdbc:sqlserver://flightbookingsystem01.database.windows.net:1433;database=flight_booking_system;user=Aritra@flightbookingsystem01;password=Flightbooking_1234;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;");//connection string
                    } catch (SQLException ex) {
                        Logger.getLogger(modifyprofile.class.getName()).log(Level.SEVERE, null, ex);
                    }



                    try {
                        stm1 =con.prepareStatement("UPDATE flight_booking.Cust_Info SET First_Name = ?, Age = ?, DOB = ?, Sex = ? WHERE Email_ID = '" + usrname + "'");//query
                        stm1.setString(1,Name);//passing variable to query
                        stm1.setString(2,Age);//passing variable to query
                        stm1.setString(3,DOB);//passing variable to query
                        stm1.setString(4, Sex);//passing variable to query
                        int s = stm1.executeUpdate();
                        if (s == 1) {
                                JOptionPane.showMessageDialog(this, "Account Updated Successfully"); //if executed successfully, dialog box will open
                                
                                
                            } else {
                                JOptionPane.showMessageDialog(this, "Account Not Updated");//else show message
                            }
                    } 

                    catch (SQLException ex) {

                        Logger.getLogger(modifyprofile.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
       
        
        
    }//GEN-LAST:event_updateActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new signout().setVisible(true); //signout
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed

        age.setText("");//set everything to initial value
        name.setText("");
        username.setText("");
        sex.setSelectedIndex(-1);
        dob.setDate(null);
        
        age.setEditable(false);//setting everything not editable
        name.setEditable(false);
        sex.setEnabled(false);
        dob.setEnabled(false);
        
        username.requestFocus();
            
        update.setEnabled(false);//set button to false

        // TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new admin_action(admin).setVisible(true);//opens admin action
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modifyprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modifyprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modifyprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modifyprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modifyprofile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JButton clear;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField name;
    private javax.swing.JComboBox<String> sex;
    private javax.swing.JLabel title;
    private javax.swing.JButton update;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

    private void Get_username() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
