/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Vatsal
 */
public class myprofile extends javax.swing.JFrame {
public String ps_mtch;
    /**
     * Creates new form myprofile
     */
    public myprofile() { //Calling a Constructor of myprofile           
        initComponents();
        Connect(); //Calling Connection with sql
        setResizable(false);
        
    }

    public myprofile(String mail, String password) { //calling constructor with login detailes 
      
        initComponents();
        
        Connect();//conncetion with the sql     
        try {
            display(mail, password); //Calling a display method and passing variable to display
        } catch (SQLException ex) {
            Logger.getLogger(myprofile.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    Connection con; //varibale
    PreparedStatement stm;// variable
    ResultSet result;//variable

    public void Connect() { //class connect which develops connection with sql databes  
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver"); //Connection driver
            con = DriverManager.getConnection("jdbc:sqlserver://flightbookingsystem01.database.windows.net:1433;database=flight_booking_system;user=Aritra@flightbookingsystem01;password=Flightbooking_1234;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;");//Connection string
                            //Connection string
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void display(String mail, String password) throws SQLException { //Display class

        String query = "Select * from flight_booking.Cust_Info where Email_ID='" + mail + "' and Pass ='" + password + "'"; //query
        try {
            Statement stm = con.createStatement(); 
            result = stm.executeQuery(query);//Executing query
        } catch (SQLException ex) {
            Logger.getLogger(myprofile.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (result.next()) { //GEtting results from the sql after execution of query
            String Name = result.getString("First_Name"); //Getting first name and storing into variable
            String Age = result.getString("Age"); //getiing age
            String emailid = result.getString("Email_ID");//getting email id
            String Dob = result.getString("DOB");//getting dob
            String Pass = result.getString("Pass");//getting password
            String Ans = result.getString("Answer");//getting answer
            String Sex = result.getString("Sex");//Getting Sex
            String sq = result.getString("SQ");//Getting Security question
         
            String Title = "Hi, " + Name; //Giving title with the username
            name.setText(Name); //setting values into txt field
            age.setText(Age); //setting age
            dob.setText(Dob);//setting dob
            email.setText(emailid);//setting email id
            pass.setText(Pass);//setting password
            ans.setText(Ans);//setting answer
            title.setText(Title);//setting title 
            sex.setSelectedItem(Sex);
            SQ.setSelectedItem(sq);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        dob = new javax.swing.JTextField();
        sex = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ans = new javax.swing.JTextField();
        SQ = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jLabel3.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 397, 36));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 120, 44));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 710, 105, 35));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("SIGN OUT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 30, 120, 44));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("NAME");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 98, 28));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("AGE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 98, 28));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("SEX");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 98, 28));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("EMAIL-ID");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 170, 28));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("DATE OF BIRTH");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 180, 28));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("PASSWORD");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 170, 28));

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 301, 28));
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, 301, 28));
        jPanel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 301, 28));

        email.setEditable(false);
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, 301, 28));

        dob.setEditable(false);
        dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobActionPerformed(evt);
            }
        });
        jPanel1.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 301, 28));

        sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        jPanel1.add(sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 84, 28));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("SECURITY QUESTION");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, 210, 28));

        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Date of Birth cannot be changed");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 360, 190, -1));

        jLabel14.setForeground(new java.awt.Color(255, 0, 51));
        jLabel14.setText("Email ID cannot be changed");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 420, 190, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("SECURITY ANSWER");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 610, 200, 28));
        jPanel1.add(ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 610, 303, 28));

        SQ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your favorite color", "Which is your favorite place", "What is your first school name", "what is your mother name" }));
        jPanel1.add(SQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 550, 303, 28));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setText("MY PROFILE");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 234, 39));

        jLabel13.setText("@PIXABAY");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 120, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.jpeg"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1070, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String Name = name.getText(); //getting name
        String Age = age.getText();//getting age
        String Dob = dob.getText();//getting dob
        String Email = email.getText(); //getting emailid
        String Pass = pass.getText();//getting password
        String Ans = ans.getText();//getting answer
        String Sex = sex.getSelectedItem().toString();//getting sex
        String Sq = SQ.getSelectedItem().toString();//getting security question

        
        
        if(Age.length()==0)//check condition if age is empty
                {
                JOptionPane.showMessageDialog(this, "Please enter your Age");
                age.setText("");
                
                age.requestFocus();
                }
        else if(Name.length()==0)//check condition if name is empty
                {
                JOptionPane.showMessageDialog(this, "Please enter your Name");
                name.setText("");
                
                name.requestFocus();
                }
        else if(Ans.length()==0){//check condition if ans is empty
                JOptionPane.showMessageDialog(this, "Please enter your Security Answer");
                ans.setText("");
                ans.requestFocus();
                }
        else{
            
             if (Pass.length() >= 5){//check condition if password in greater than 5
                    try {
                        stm = con.prepareStatement("UPDATE flight_booking.Cust_Info SET First_Name = ?, Age = ?, DOB = ?, Pass = ?, Answer = ?, SQ = ?, Sex = ? WHERE Email_ID = ?"); //string query
                        stm.setString(1, Name);//passing variable to query
                        stm.setString(2, Age);//passing variable to query
                        stm.setString(3, Dob);//passing variable to query
                        stm.setString(4, Pass);//passing variable to query
                        stm.setString(5, Ans);//passing variable to query
                        stm.setString(6, Sq);//passing variable to query
                        stm.setString(7, Sex);//passing variable to query
                        stm.setString(8, Email);//passing variable to query

                        int s = stm.executeUpdate(); //Executing query status

                        if (s == 1) {
                            JOptionPane.showMessageDialog(this, "Account Updated Successfully"); //if executed successfully, dialog box will open

                        } else {
                            JOptionPane.showMessageDialog(this, "Account Not Updated");
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(myprofile.class.getName()).log(Level.SEVERE, null, ex);
                    }
             }
              else {
                JOptionPane.showMessageDialog(this, "Password Does not match or The Password is too Small");
             }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String username=email.getText(); //getting username
        String password=pass.getText();//getting password
        String condition="true";//getting condition
        String Name=name.getText();//getting name
        
        new Home_page(condition,username,password,Name).setVisible(true); //open homepage with the name
        dispose();//this is closed
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

                    new signout().setVisible(true); //signout
                       dispose(); //this is dispose
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new myprofile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> SQ;
    private javax.swing.JTextField age;
    private javax.swing.JTextField ans;
    private javax.swing.JTextField dob;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField pass;
    private javax.swing.JComboBox<String> sex;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
