
import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



/**
 *
 * @author sachi
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    
    //declaring variables 
    public String arrival_name;
    public String departure_name;
    public String traveldate;
    public String str_fid;
    public String str_date[];
    public String str_dateprint;
    public String date_month;
    public String date_num;
    public String pswdmatch="true";
    public String username;
    public String password;
    public String Price;
    public String usr_name;
    public String open;
    public String b_id;
    public String b_arrival;
    public String b_departure;
    public String selected_date;
    public String selected_price;
    public String Passengername;
    public String birthdate;
    public int passnum;
    public String gender;
    public int availableseats;
    public int seatcapacity;
    public int bookedseats;
    public double initialprice;
    public Date date1;

    
    
    
    Connection con;
    PreparedStatement stm;
    PreparedStatement stl;
    public Payment() {
        initComponents();
    }
    
    
    //creating components for payment details
    public Payment(String val1,String val2,String val3,String val4, String val5, String val6, String val7, String val8,String val9,String val10, String val11, String val12, int val13, String val14){
        
        initComponents();
         this.b_id=val1; //Flight id passed by trsvel info
         this.b_arrival=val2; //Arrival detailes passed 
         this.b_departure=val3;//Departure detailes passed
         this.selected_date=val4; //Date passed by
         this.open=val5; //Login passed
         this.username=val6;//Username passed 
         this.password=val7;//password passed
         this.usr_name=val8;//id passed 
         this.selected_price=val9;//price passed 
         this.traveldate = val10;//travel date
         this.Passengername = val11;//passagner name passed
         this.birthdate = val12;//birthday passed
         this.passnum = val13;//passport number passed
         this.gender = val14;//gender passed
         
         
         //setting data into labels
         from.setText(b_departure);
         to.setText(b_arrival);
         date.setText(traveldate);
         price.setText("CAD "+ selected_price );
         
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Cardname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        CVV = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        from = new javax.swing.JLabel();
        to = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Card = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 0, -1, 26));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("PAYMENT");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 210, 50));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("SIGN-OUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, 120, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("HOME");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 100, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("  Card Details");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 170, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Debit/Credit Card Number");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 476, 31, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Card Holder's Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 163, -1));

        Cardname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardnameActionPerformed(evt);
            }
        });
        jPanel1.add(Cardname, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 217, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("CVV");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, -1, 25));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Date of Expiry");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 92, -1));

        jLabel18.setForeground(new java.awt.Color(255, 0, 51));
        jLabel18.setText("MM/YY Format");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 110, 20));

        jLabel19.setForeground(new java.awt.Color(255, 0, 51));
        jLabel19.setText("16 Digits Only");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 200, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 80, 27));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 70, 27));

        CVV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CVVKeyPressed(evt);
            }
        });
        jPanel1.add(CVV, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 51, 25));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Flight Details");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 11, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("FROM");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 50, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("TO");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 104, 36, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Price");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 75, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Date");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 50, -1));

        price.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 150, 20));

        from.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(from, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 150, 20));

        to.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(to, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 150, 20));

        date.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 150, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 230, 310, 250));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("SUBMIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, 120, 40));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("RESET");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, 100, 40));

        Card.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardActionPerformed(evt);
            }
        });
        Card.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CardKeyPressed(evt);
            }
        });
        jPanel1.add(Card, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 217, -1));

        jLabel17.setText("@PIXABAY");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 120, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/white.jpg"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 90));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.jpeg"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 90, 1060, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     void update_available_seats(){//update for seats available
         Connection conn; //declaring variables
        ResultSet rs;
        ResultSet rs1;
        
      try { //Connection with the Azure SQL
        
         
         
        date1 = new java.sql.Date(new SimpleDateFormat("yyyy-MM-dd").parse(traveldate).getTime());//geting date
          System.out.println("dt payment "+date1);//setting the payment date
          System.out.println("flight id ="+b_id);
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver"); //Connection driver
            conn = DriverManager.getConnection("jdbc:sqlserver://flightbookingsystem01.database.windows.net:1433;database=flight_booking_system;user=Aritra@flightbookingsystem01;password=Flightbooking_1234;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;");//Connection string
            java.sql.Statement stat = conn.createStatement();
            String SelectQuery = "select b.availableseats,c.seatingcapacity,a.Price from flight_booking.Flight_Detail a inner join flight_booking.seatavailabilty b on a.f_id=b.f_id inner join flight_booking.aircraft_details c on c.aircraft_modelname=a.aircraft_model where a.f_id ='"+b_id+"' and b.deptdate='"+date1+"' "; //Query Statement
            rs = stat.executeQuery(SelectQuery);//Executing Query
            while (rs.next()) {//Displaying results 
                System.out.println("hit");
                 availableseats = rs.getInt(1);//availabe seats 
                 seatcapacity=rs.getInt(2);//total capacity
                 initialprice=rs.getInt(3);//price
                 
                 
                 
                System.out.println("availableseats = "+availableseats);
                System.out.println("seatcapacity = "+seatcapacity);
                System.out.println("initialprice = "+initialprice);
                bookedseats=(seatcapacity-availableseats)+1; //variable booked seats
                 
                if (availableseats>0)//if avaiable seats are higher than 0
                {
                   System.out.println("hit2"); 
                   availableseats-=1;
                
                String update_seats = "update flight_booking.seatavailabilty set availableseats='"+availableseats+"',bookedseats='"+bookedseats+"' where f_id ='"+b_id+"' and deptdate='"+date1+"'";//query
                rs1=stat.executeQuery(update_seats);//execute the query
                }
                else {};
                                         
            }
            
      
        } catch (Exception e) 
        {

        }
     
     }
     
     
     void dynamicpricing(){//create class dyanamic pricing
     
         
     double percentage_booked_seats=((double)bookedseats/seatcapacity)*100;//convert the seats into percentage of booked flights
     double newflightprice;//create variable
     if (percentage_booked_seats>0 && percentage_booked_seats<=10)
     {//condition if booked seats are between 0 and 10
     newflightprice=initialprice;//new price
     }
     else if (percentage_booked_seats>10 && percentage_booked_seats<=20){//condition if booked seats are between 10 and 20
     newflightprice=1.1*initialprice;//new price
     }
     else if (percentage_booked_seats>20 && percentage_booked_seats<=30)
     {//condition if booked seats are between 20 and 30
         newflightprice=1.2*initialprice;//new price
     }
     else if (percentage_booked_seats>30 && percentage_booked_seats<=40)
     {//condition if booked seats are between 30 and 40
         newflightprice=1.3*initialprice;//new price
     }
     else if (percentage_booked_seats>40 && percentage_booked_seats<=50)
     {//condition if booked seats are between 40 and 50
         newflightprice=1.4*initialprice;//new price
     }
     else if (percentage_booked_seats>50 && percentage_booked_seats<=60)
     {//condition if booked seats are between 50 and 60
         newflightprice=1.5*initialprice;//new price
     }
     else if (percentage_booked_seats>60 && percentage_booked_seats<=70)
     {//condition if booked seats are between 60 and 70
         newflightprice=1.6*initialprice;//new price
     }
     else if (percentage_booked_seats>70 && percentage_booked_seats<=80)
     {//condition if booked seats are between 70 and 80
         newflightprice=1.7*initialprice;//new price
     }
     else if (percentage_booked_seats>80 && percentage_booked_seats<=90)
     {//condition if booked seats are between 80 and 90
         newflightprice=1.8*initialprice;//new price
     }
     else if (percentage_booked_seats>90 && percentage_booked_seats<=100)
     {//condition if booked seats are between 90 and 100
         newflightprice=1.9*initialprice;//new price
     }
     
     else {
     newflightprice=initialprice; //new flight price
     }
     System.out.println("% = "+percentage_booked_seats);
     System.out.println(newflightprice);
     try {
         
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver"); //Connection driver
            con = DriverManager.getConnection("jdbc:sqlserver://flightbookingsystem01.database.windows.net:1433;database=flight_booking_system;user=Aritra@flightbookingsystem01;password=Flightbooking_1234;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;");//Connection string
                
                stm = con.prepareStatement("update flight_booking.seatavailabilty set currentprice='"+newflightprice+"',prcntgebookedseats='"+percentage_booked_seats+"'where f_id ='"+b_id+"' and deptdate='"+date1+"'" ); //query
                stm.executeUpdate();//execute query
                
                
             
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Travel_Info.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Travel_Info.class.getName()).log(Level.SEVERE, null, ex);
            }
     
     
     }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    new signout().setVisible(true); //signout
    this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CardnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CardnameActionPerformed
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        
        
        String emailid=username; //private variable emailid
        int fid = Integer.parseInt(b_id);
        String destination_arrival=b_arrival;
        String destination_departure=b_departure;
        String price=selected_price;
        String date=traveldate;
            //getting data from the window such as card no, name, date of expiry and cvv
            String Cardno = Card.getText();
            String namecard = Cardname.getText();
           // String doe = DOE.getText();
            String cvv = CVV.getText();
         if(namecard.length()==0)
                {
                JOptionPane.showMessageDialog(this, "Please enter your Name displayed on card");
                }
         else{
            
            if(Cardno.length() == 16 & cvv.length() == 3){ //card length should be 16 only and cvv should be 3 only
                
                 
                                  
                 
                 try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver"); //Connection driver
            con = DriverManager.getConnection("jdbc:sqlserver://flightbookingsystem01.database.windows.net:1433;database=flight_booking_system;user=Aritra@flightbookingsystem01;password=Flightbooking_1234;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;");//Connection string
                
                stm = con.prepareStatement("INSERT INTO flight_booking.Passenger_Info(Email_ID,flight_id,arrival,departure,Passenger_name,birth_date,passport,Sex,price,traveldate,status,bookingdate,bookingtime)values(?,?,?,?,?,?,?,?,?,?,'active',Convert(Date, SWITCHOFFSET(SYSDATETIMEOFFSET(), '-05:00')),Convert(Time, SWITCHOFFSET(SYSDATETIMEOFFSET(), '-05:00')))"); //query
                //inserting into the table with follwing data
               
                
                stm.setString(1,emailid);
                stm.setInt(2,fid);
                stm.setString(3,destination_arrival);
                stm.setString(4,destination_departure);
                stm.setString(5,Passengername);
                stm.setString(6, birthdate);
                stm.setInt(7, passnum);
                stm.setString(8, gender);
                stm.setString(9, price);
                stm.setString(10, date);
                 
                stm.executeUpdate();
                update_available_seats();
                dynamicpricing();
                
                
             
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Travel_Info.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Travel_Info.class.getName()).log(Level.SEVERE, null, ex);
            }
                 
                 
                 new Confirmation(b_id,b_arrival,b_departure,selected_date,open,username,password,usr_name,selected_price,traveldate).setVisible(true); //if above condition is satisfied, Confirmation page will open
                 this.dispose(); 
                 
                 
            }
            
            
            
            
            else{
                JOptionPane.showMessageDialog(this, "Please Enter Correct Information");//else error dialog box will be displayed
                //setting all to initial values
                Card.setText("");  
                Cardname.setText(""); 
            //    DOE.setText(""); 
                CVV.setText("");
                Card.requestFocus();
            }
         }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
             new Home_page(open,username,password,usr_name).setVisible(true); //Clicking home button opens home page with login details to set username on title
              this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            //clear button clears text field
            Card.setText("");  
            Cardname.setText(""); 
            //DOE.setText(""); 
            CVV.setText(""); 

// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void CardKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CardKeyPressed
        //to enter the values into card no, only input it can take is number and not any alphabets
        //also, max card no length is 16 and no more than that
        String cardnumber = Card.getText();
        int length = cardnumber.length();
        char c = evt.getKeyChar();
        if(evt.getKeyChar()>= '0' && evt.getKeyChar()<='9')
        { 
            if(length<16){
            Card.setEditable(true);
            }else{
                Card.setEditable(false);
                Cardname.requestFocus();
                 }
        }else{
              if( evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE ||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE ){
              Card.setEditable(true);

              }else{Card.setEditable(false);
              getToolkit().beep();//beep sound will come if any key is pressed
        }
}        // TODO add your handling code here:
    }//GEN-LAST:event_CardKeyPressed

    private void CVVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CVVKeyPressed
         //to enter the values into cvv no, only input it can take is number and not any alphabets
        //also, max card no length is 3 and no more than that
        String cvvnumber= CVV.getText();
        int length= cvvnumber.length();
        char c = evt.getKeyChar();
        if(evt.getKeyChar()>= '0' && evt.getKeyChar()<='9'){
        if(length<3){
        CVV.setEditable(true);
        }else{CVV.setEditable(false);
             }
        }else{
        if( evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE ||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE ){
              CVV.setEditable(true);

              }else{CVV.setEditable(false);
              getToolkit().beep(); //beep will sound when key is pressed
        }
}
// TODO add your handling code here:
    }//GEN-LAST:event_CVVKeyPressed

    private void CardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField CVV;
    private javax.swing.JTextField Card;
    private javax.swing.JTextField Cardname;
    private javax.swing.JLabel date;
    private javax.swing.JLabel from;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel price;
    private javax.swing.JLabel to;
    // End of variables declaration//GEN-END:variables
}
