/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import com.mysql.cj.jdbc.result.ResultSetMetaData;
import javax.swing.*; 
import java.awt.*; 
import java.awt.event.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.table.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Vatsal
 */
public class Travel_Info extends javax.swing.JFrame {

    //Declaring piblic variables
    
    public String arrival_name;
    public String departure_name;
    public String traveldate;
    public String str_fid;
    public String str_date[];
    public String str_dateprint;
    public String date_month;
    public String date_num;
    public String pswdmatch="true";
    public String username;
    public String password;
    public String Price;
    public String usr_name;
    public String open;
    public String b_id;
    public String b_arrival;
    public String b_departure;
    public String selected_date;
    public String selected_price;
    public String day;
    /**
     * Creates new form Travel_Info
     */
    public Travel_Info() {
        initComponents();
    }

    
    Connection con;
    PreparedStatement stm;
    PreparedStatement stl;
    
    public Travel_Info(String val1,String val2,String val3,String val4, String val5, String val6, String val7, String val8,String val9, String val10,String val11)
    {//constructor for Travel_Info
        
        initComponents();
         this.b_id=val1; //Flight id passed by list of flight
         this.b_arrival=val2; //Arrival detailes passed
         this.b_departure=val3;//Departure detailes passed
         this.selected_date=val4; //Date passed
         this.open=val5; //Login passed
         this.username=val6;//Username passed
         this.password=val7;//password passed
         this.usr_name=val8;//id passed
         this.selected_price=val9;//price passed
         this.traveldate = val10;//date passed
         this.day=val11;//day passed
      
         
         title.setText("Hi, " + usr_name); //setting text for button hi, username   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jtiitle = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pdob = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        passport = new javax.swing.JTextField();
        psex = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel7.setText("@PIXABAY");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 86, 36));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 86, 36));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("SIGN OUT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, -1, 36));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("CONFIRM");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 550, 170, 50));

        jtiitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jtiitle.setText("TRAVEL INFORMATION");
        jPanel1.add(jtiitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 438, 36));

        title.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 230, 36));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("DATE OF BIRTH");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 198, 27));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("PASSENGER NAME");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 198, 27));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("PASSPORT INFORMATION");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 198, 27));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("SEX");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 198, 27));
        jPanel1.add(pdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 280, 30));

        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("Only Integrers");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 360, 110, -1));

        pname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 280, 30));

        passport.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        passport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passportActionPerformed(evt);
            }
        });
        jPanel1.add(passport, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 280, 30));

        psex.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        psex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Sex...", "Male", "Female", "Other" }));
        psex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psexActionPerformed(evt);
            }
        });
        jPanel1.add(psex, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 280, 30));

        jLabel8.setText("@PIXABAY");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 140, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/white.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1050, 120));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.jpeg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 120, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, -2, 1040, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passportActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       new Home_page(open,username,password,usr_name).setVisible(true); //Clicking home button opens home page with login details to set username on title
                        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       new signout().setVisible(true); //signout
                       dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            Date date1 = new java.sql.Date(new SimpleDateFormat("yyyy-MM-dd").parse(selected_date).getTime());
            new List_flights(b_arrival,b_departure,traveldate,open,username,password,usr_name,selected_price,day,date1).setVisible(true);//clicking on button opens list of flight
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Travel_Info.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(Travel_Info.class.getName()).log(Level.SEVERE, null, ex);
        }
       dispose();
     
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
            String Passengername=pname.getText(); //getting passenger name from window




           
        
        
        
        if(pname.getText().length() == 0){//check for condition if value is empty
            JOptionPane.showMessageDialog(this, "Please enter Passenger's Name");
        }  
        
        else if(pdob.getDate() == null){//check for condition if value is empty
            JOptionPane.showMessageDialog(this, "Please enter Passenger's Date of Birth");
        }
        
        else if(passport.getText().length() == 0){//check for condition if value is empty
            JOptionPane.showMessageDialog(this, "Please enter passport number");
        }
        
        else if(psex.getSelectedIndex() == 0){//check for condition if value is empty
            JOptionPane.showMessageDialog(this, "Please Select Sex");
        }
         
        
            else{ //execute the following statement
            
            java.sql.Date Date = new java.sql.Date(pdob.getDate().getTime()); //Used calender jar file to get date and time
            String birthdate = Date.toString();//converting to string


            long today = System.currentTimeMillis();//get today's date
            java.sql.Date tdate = new java.sql.Date(today);//convert it in date format
            String todaysdate=tdate.toString();
            
            
                if(birthdate.compareTo(todaysdate) > 0){//check for condition if birthdate is greater than today's date
                            JOptionPane.showMessageDialog(this, "Passenger's age cannot be greater than today's date. Please check date of birth entered");

                    }


                else{//if not execute following

                    int passnum = Integer.parseInt(passport.getText());//getting passport number from window
                    String gender=psex.getSelectedItem().toString();//getting sex from window
                    String price=selected_price;
                    String date=traveldate;
                    //System.out.println(date);


                        if (passport.getText().length() > 5){//minimum length of the password should be 5

                         new Payment(b_id,b_arrival,b_departure,selected_date,open,username,password,usr_name,selected_price,traveldate,Passengername,birthdate,passnum,gender).setVisible(true);//opening of payment page
                         this.dispose();

                        }
                        else{
                            JOptionPane.showMessageDialog(this, "Incorrect Passport Details");//message is displayed if passport is incorrect
                            passport.requestFocus();    

                        }





                }
                    }
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void psexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psexActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Travel_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Travel_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Travel_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Travel_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Travel_Info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jtiitle;
    private javax.swing.JTextField passport;
    private com.toedter.calendar.JDateChooser pdob;
    private javax.swing.JTextField pname;
    private javax.swing.JComboBox<String> psex;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
